# Generated by Django 2.0.1 on 2018-01-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170923_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='service.TagsEntry'),
        ),
    ]
